message:
  supportedMessageTypes:
    - identify
    - alias
    - track
    - screen
    - group
    - page
  identify:
    transformation:
      mapperPath: ./mapping/identify.yaml
      postMapper:
        name: "commonPostMapper"
      response:
        endpoint: https://app.posthog.com/batch
        method: POST
        format: JSON
        headers:
          key:
          Content-Type: "application/json"
  alias:
    transformation:
      mapperPath: ./mapping/alias.yaml
      postMapper:
        name: "commonPostMapper"
      response:
        endpoint: https://app.posthog.com/batch
        method: POST
        format: JSON
        headers:
          key:
          Content-Type: "application/json"
  track:
    transformation:
      mapperPath: ./mapping/track.yaml
      postMapper:
        name: "commonPostMapper"
      response:
        endpoint: https://app.posthog.com/batch
        method: POST
        format: JSON
        headers:
          key:
          Content-Type: "application/json"
  group:
    transformation:
      mapperPath: ./mapping/group.yaml
      postMapper:
        name: "commonPostMapper"
      response:
        endpoint: https://app.posthog.com/batch
        method: POST
        format: JSON
        headers:
          key:
          Content-Type: "application/json"
  page:
    transformation:
      mapperPath: ./mapping/page.yaml
      postMapper:
        name: "commonPostMapper"
      response:
        endpoint: https://app.posthog.com/batch
        method: POST
        format: JSON
        headers:
          key:
          Content-Type: "application/json"
  screen:
    transformation:
      mapperPath: ./mapping/screen.yaml
      postMapper:
        name: "commonPostMapper"
      response:
        endpoint: https://app.posthog.com/batch
        method: POST
        format: JSON
        headers:
          key:
          Content-Type: "application/json"
